### ISSUE TITLE
Issue with when starting the agent and collectd

### ISSUE THREAD

**Issue by txynidakis** [christiangda/ansible-role-amazon-cloudwatch-agent#20]
Hi, the role is brilliant and works as presented.

this is a minor tweak suggestion when enabling the collectd service.

when running the following command. 
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json  -s

the following error presented 
```
/opt/aws/amazon-cloudwatch-agent/bin/config-downloader --output-dir /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d --download-source file:/opt/aws/amazon-cloudwatch-agent/bin/config.json --mode ec2 --config /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml --multi-config default
Successfully fetched the config and saved in /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/file_config.json.tmp
Start configuration validation...
/opt/aws/amazon-cloudwatch-agent/bin/config-translator --input /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json --input-dir /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d --output /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml --mode ec2 --config /opt/aws/amazon-cloudwatch-agent/etc/common-config.toml --multi-config default
2020/02/09 11:10:04 Reading json config file path: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.d/file_config.json.tmp ...
Valid Json input schema.
I! Detecting runasuser...
No csm configuration found.
No log configuration found.
Configuration validation first phase succeeded
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent -schematest -config /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml
Configuration validation second phase failed
======== Error Log ========
2020/02/09 11:10:04 I! AmazonCloudWatchAgent Version 1.232905.0.
2020/02/09 11:10:04 E! Error parsing /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.toml, open /usr/share/collectd/types.db: no such file or directory
```

I found the fix here https://linuxacademy.com/community/show/30746-problem-in-installing-cloudwatchagent/

The solution was to run the 2 commands
sudo mkdir /usr/share/collectd
sudo touch /usr/share/collectd/types.db

The suggestion is to include a play in the configure.yaml

**Comment by christiangda** [comment]
Hi @txynidakis ,

Thank you very much for your help to this role, I'll check as soon as possible and I'll implement the solution if I can.

**Comment by christiangda** [comment]
Hi @txynidakis ,

Today I've read your "reported issue" carefully, and yes, the solution is to install `collectd` package before install `aws cloudwatch agent`.
In version 1.x.x of this role, I was installing it as a default package, but many people suggest to me remove it because no all ones use AWS [cloudwatch agent collectd configuration](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-Agent-custom-metrics-collectd.html) in its systems, and this is the reason why we are in version 2.x.x.

The role version 2.x.x detects if your agent configuration has the world `collectd` and install it automatically, I've tested it and works for me, it doesn't work for you?

See the last line of this fragment of the role file `https://github.com/christiangda/ansible-role-amazon-cloudwatch-agent/blob/master/tasks/install-redhat.yml`
```yaml
- name: Install {{ cwa_package }} dependencies (it depend on EPEL Repositories, you ned to take care of that)
  block:
    - name: Install "{{ cwa_dependencies_packages }}" dependency on Amazon 1/2
      yum:
        name: "{{ cwa_dependencies_packages }}"
        state: present
      register: package_ok
      retries: "{{ cwa_global_downloads_retries }}"
      delay: "{{ cwa_global_downloads_delay }}"
      until: package_ok is success
      when: >
        ansible_os_family == 'RedHat' and
        ansible_distribution == 'Amazon'
      tags:
        - install

    - name: Install "{{ cwa_dependencies_packages }}" dependency on ReHat/CentOS 6/7/8
      yum:
        name: "{{ cwa_dependencies_packages }}"
        state: present
      register: package_ok
      retries: "{{ cwa_global_downloads_retries }}"
      delay: "{{ cwa_global_downloads_delay }}"
      until: package_ok is success
      when: >
        ansible_os_family == 'RedHat' and (
          ansible_distribution == 'CentOS' or
          ansible_distribution == 'RedHat'
        ) and (
          ansible_distribution_major_version == '8' or
          ansible_distribution_major_version == '7' or
          ansible_distribution_major_version == '6'
        )
      tags:
        - install
  when: cwa_conf_json_file_content is search("collectd")
```
